# Generated by Django 3.2.7 on 2022-02-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_auto_20220211_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
